# Default configuration for extension with alias: "antispam"
antispam:

    # Global default for whether included components should cause hard failures
    passive:              false

    # Global default for whether included components issue verbose or stealthy error messages
    stealth:              false
    quarantine:
        dir:                  '%kernel.project_dir%/var/quarantine'

    # A named list of different profiles used throughout your application
    profiles:

        # Prototype: Name the profile
        name:

            # Defines whether measures in this profile issue stealthy error messages
            stealth:              true

            # Passive mode will not make any of the included checks actually fail validation, they will still be logged
            passive:              false

            # Defines whether to disallow content resembling markup languages like HTML and BBCode
            banned_markup:
                html:                 true
                bbcode:               true

            # Simple array of phrases which are rejected when encountered in a submitted text field
            banned_phrases:       []

            # Banned script types, like Cyrillic or Arabic (see docs for commonly used ISO 15924 names)
            banned_scripts:
                scripts:              []
                max_characters:       null
                max_percentage:       0

            # Inject an invisible honeypot field in forms, baiting spambots to fill it in
            honeypot:

                # Base name of the injected field
                field:                ~ # Required
                attributes:

                    # Prototype
                    name:                 ~

            # Verify that time between retrieval and submission of a form is within human boundaries
            timer:

                # Base name of the injected field
                field:                _validation
                min:                  3
                max:                  3600

            # Configure limits to number of URLs permitted in text fields
            url_count:

                # Maximum number of URLs accepted per text field
                max:                  null

                # Maximum number of identical URLs accepted per text field
                max_identical:        null

