name: automated-testing

on:
  pull_request:
  push:
    branches:
      - master
  schedule: # Ensure weekly test also if no pushes happen to keep up with dependencies
    - cron: 0 10 * * 1

jobs:
  run:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental || matrix.dependencies == 'beta' }}
    strategy:
      fail-fast: false
      matrix:
        php:
          - '8.1'
          - '8.2'
        dependencies: [ lowest, stable, beta ]
        experimental: [ false ]
        include:
          - description: 'stable dependencies'
            dependencies: stable
          - description: 'lowest dependencies'
            dependencies: lowest
          - description: 'beta/RC dependencies'
            dependencies: beta
          - description: 'nightly with stable dependencies'
            php: 8.3
            experimental: true

    name: PHP ${{ matrix.php }} ${{ matrix.description }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: intl, mbstring
          ini-values: zend.assertions=1

      - name: Allow beta dependencies
        run: composer config minimum-stability beta
        if: matrix.dependencies == 'beta'

      - name: Install dependencies
        run: composer update ${{ (matrix.dependencies == 'lowest') && '--prefer-lowest --prefer-stable' || ''}}

      - name: Run PHPStan static analysis
        run: vendor/bin/phpstan
        if: ${{ matrix.dependencies == 'stable' && !matrix.experimental }}

      - name: Check for dangerous and broken dependencies
        run: composer audit
        if: ${{ matrix.dependencies == 'stable' && !matrix.experimental }}

      - name: Run automated tests
        run: vendor/bin/phpunit --coverage-text --coverage-xml build/coverage-xml --coverage-cobertura build/cobertura.xml

      - name: Code Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: build/cobertura.xml
          badge: true
          fail_below_min: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: '90 98'

      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: code-coverage-results.md

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Run infection tests
        run: vendor/bin/infection --threads=max
        if: ${{ matrix.dependencies == 'stable' && !matrix.experimental }}
